

//com.miele.xgw3000.gateway.hdm.deviceclasses.Miele

//protected final int JSON_RPC_PORT = 2810;
//protected final String JSON_RPC_MULTICAST_IP1 = "239.255.68.139";
//protected final String JSON_RPC_MULTICAST_IP2 = "224.255.68.139";


var WASHING_MACHINE = 1;
var WASHER_DRYER = 24;
var TUMBLE_DRYER = 2;
var DISHWASHER = 7;
var RANGE_COOKER = 10;
var RANGE_COOKER_MICROWAVE = 11;
var OVEN = 12;
var MICROWAVE_OVEN = 16;
var OVEN_MICROWAVE_COMBI = 13;
var STEAM_OVEN_COMBI = 31;
var STEAM_OVEN = 15;
var STEAM_OVEN_MICROWAVE = 45;
var COFFEE_MAKER = 17;
var HOB = 14;
var HOB_INDUCTION = 27;
var HOOD = 18;
var WINE_TEMPERATURE_CABINET = 33;
var WINE_TEMPERATURE_STORAGE = 34;
var WINE_STORAGE_CABINET = 32;
var REFRIGERATOR = 19;
var FREEZER = 20;
var REFRIGERATOR_FREEZER = 21;

var MIELE_DEVICE_TYPES = [
    WASHING_MACHINE,
    WASHER_DRYER,
    TUMBLE_DRYER,
    DISHWASHER,
    RANGE_COOKER,
    RANGE_COOKER_MICROWAVE,
    OVEN,
    MICROWAVE_OVEN,
    OVEN_MICROWAVE_COMBI,
    STEAM_OVEN_COMBI,
    STEAM_OVEN,
    STEAM_OVEN_MICROWAVE,
    COFFEE_MAKER,
    HOB,
    HOB_INDUCTION,
    HOOD,
    WINE_TEMPERATURE_CABINET,
    WINE_TEMPERATURE_STORAGE,
    WINE_STORAGE_CABINET,
    REFRIGERATOR,
    FREEZER,
    REFRIGERATOR_FREEZER
];

var STATE_OFF = 1;
var STATE_STAND_BY = 2;
var STATE_PROGRAMMED = 3;
var STATE_PROGRAMMED_WAITING_TO_START = 4;
var STATE_RUNNING = 5;
var STATE_PAUSE = 6;
var STATE_END_PROGRAMMED = 7;
var STATE_FAILURE = 8;
var STATE_PROGRAMME_INTERRUPTED = 9;
var STATE_IDLE = 10;
var STATE_RINSE_HOLD = 11;
var STATE_SERVICE = 12;
var STATE_SUPERFREEZING = 13;
var STATE_SUPERCOOLING = 14;
var STATE_SUPERHEATING = 15;
var STATE_DEFAULT = 144;
var STATE_LOCKED = 145;
var STATE_SUPERCOOLING_SUPERFREEZING = 146;

var MIELE_DEVICE_STATES = [
    STATE_FAILURE,
    STATE_RUNNING,
    STATE_PROGRAMMED_WAITING_TO_START,
    STATE_RINSE_HOLD,
    STATE_PAUSE,
    STATE_PROGRAMME_INTERRUPTED,
    STATE_END_PROGRAMMED,
    STATE_PROGRAMMED,
    STATE_SERVICE,
    STATE_LOCKED,
    STATE_STAND_BY,
    STATE_OFF
];

function isWineDevice(mieleId) {
    return mieleId == 32 || mieleId == 33 || mieleId == 34;
}

function isCoolingDevice(mieleId) {
    return mieleId == 19 || mieleId == 20 || mieleId == 21 || mieleId == 22;
}

